del ja/
del IronPython.dll
del p4api.net.dll
del WeifenLuo.WinFormsUI.Docking.dll
del SharpDX.Direct2D1.dll
del ActiproSoftware.Shared.Net20.dll
del ActiproSoftware.SyntaxEditor.Addons.DotNet.Net20.dll
del ActiproSoftware.SyntaxEditor.Net20.dll
del ActiproSoftware.WinUICore.Net20.dll
del Atf.Perforce.dll
del Atf.Perforce.pdb
del Bespoke.Common.dll
del Bespoke.Common.Osc.dll
del EngineCLR.dll.metagen
del IronPython.dll
del IronPython.Modules.dll
del IronPython.Modules.xml
del IronPython.xml
del libcrashreport_net.dll
del Microsoft.Dynamic.dll
del Microsoft.Dynamic.xml
del Microsoft.QualityTools.Testing.Fakes.dll
del Microsoft.Scripting.dll
del Microsoft.Scripting.xml
del p4api.net.dll
del p4api.net.pdb
del p4api.net.xml
del SharpDX.Direct2D1.dll
del SharpDX.dll
del SharpDX.DXGI.dll
del Wws.LiveConnect.1.0.4406.32783.Fakes.fakesconfig